### ISSUE TITLE
generate base entity structures

### ISSUE THREAD

**Issue by sonercirit** [nodgroup/pickle-user#8]
General structure will be something like this:

1) User (id (PK), user name (unique), password (salted and hashed!))
2) Role (id (PK), role name (unique))
3) Permission (id (PK), permission name (unique)) - the tabs / screens / actions goes here
4) User To Role (id (PK), user id, role id)
5) Role to Permission (id (PK), role id, permission id)

@ErkanEREN @batuhan @BatuhanW any opinions on this? also any extra fields to add?
@BatuhanW what extra fields we will need for sure on a generic front-end? (e.g. description for roles and permissions seems needed but not sure) keep in mind this project will be used across different projects so keeping it small and simple should be prioritized. we can always add stuff later

**Comment by coneforapine** [comment]
I don't know what will give us more performance but iirc we can use json column from typeorm for role and permission columns under user.

I think if we use json columns there will be no need for user to role and role to permissions tables since we can check it on the parsed entity data.

**Comment by sonercirit** [comment]
We've discussed that before but decided that splitting the role / permission system into different tables will be better for scalability.

**Comment by ErkanEREN** [comment]
I think having both role and permission is an overkill. What we need to do is to decide whatbased our authorisation will be? Role based, privilege/permission based, screen (menu) based etc...

The bases we can select are not so different from eachother however all comes with pros and cons.

What will be the most common scenarios the authorisation system will face?

**Comment by sonercirit** [comment]
if we do just a permission based system, managing roles via dashboard (i.e. end-user) and/or coding dashboard will be harder

but if we just do roles how will we define which permissions does each role have? (e.g. moderator role has edit permission, reader role does not have edit permission) we will need to separate these cases somehow.

**Comment by ErkanEREN** [comment]
this makes sense, initially, I haven't thought that aspect of it. I have one last question, can a user have some roles and "additional" permissions?

**Comment by sonercirit** [comment]
Then you would create a role with additional permissions and assign it to the user. One user can have multiple roles.
